# Monthly pull requests for dependency updates (security fixes come sooner).
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
