// swift-tools-version: 5.10
// BookshelfKit: the Swift side of the macOS app that isn't views. It wraps
// the shared Rust core (bookshelf-ffi), holds the app's models, and the
// writing page's text engine (AppKit text, no windows), so all of it can be
// tested with `swift test`.
import PackageDescription

let package = Package(
    name: "BookshelfKit",
    platforms: [.macOS(.v14)],
    products: [
        .library(name: "BookshelfKit", targets: ["BookshelfKit"]),
    ],
    targets: [
        // The Rust core, built by apple/scripts/build-xcframework.sh (not committed).
        .binaryTarget(name: "bookshelf_ffiFFI", path: "Frameworks/bookshelf_ffiFFI.xcframework"),
        // Generated by scripts/gen-bindings.sh; don't edit by hand.
        .target(
            name: "BookshelfFFI",
            dependencies: ["bookshelf_ffiFFI"],
            linkerSettings: [
                // Used by the Rust networking code (proxy settings, TLS).
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
        .target(name: "BookshelfKit", dependencies: ["BookshelfFFI"]),
        .testTarget(name: "BookshelfKitTests", dependencies: ["BookshelfKit"]),
    ]
)
